In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

In [99]:
from __future__ import division
from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn
import numpy as np
pd.options.display.max_rows = 12
np.set_printoptions(precision=4, suppress=True)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(12, 6))

In [2]:
ints = np.ones(10,dtype=np.uint16)
floats = np.ones(10,dtype=np.float32)0000000o

In [3]:
np.issubdtype(ints.dtype,np.integer)

True

In [4]:
np.issubdtype(floats.dtype,np.floating)

True

In [5]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [6]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
arr = np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
other_arr = np.ones((3,5))
other_arr.shape

(3, 5)

In [12]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [22]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr1.shape

(2, 3)

In [25]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
from numpy.random import randn

In [30]:
arr = randn(5,2)
arr

array([[-0.8635,  2.4407],
       [-0.155 , -0.2637],
       [ 0.0534, -0.1264],
       [-1.1074, -0.4961],
       [-0.732 ,  0.5658]])

In [31]:
first, second, third = np.split(arr,[1,3])

In [32]:
first

array([[-0.8635,  2.4407]])

In [33]:
second

array([[-0.155 , -0.2637],
       [ 0.0534, -0.1264]])

In [34]:
third

array([[-1.1074, -0.4961],
       [-0.732 ,  0.5658]])

In [35]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = randn(3,2)

In [36]:
np.r_[arr1,arr2]

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [-0.1241, -0.4022],
       [-1.3019, -0.6685],
       [ 0.6171, -0.4721]])

In [37]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [-0.1241, -0.4022,  3.    ],
       [-1.3019, -0.6685,  4.    ],
       [ 0.6171, -0.4721,  5.    ]])

In [38]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [39]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [40]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [41]:
arr = randn(2,2)
arr

array([[ 0.2974, -0.6587],
       [-1.4271, -0.7679]])

In [42]:
arr.repeat(2,axis=0)

array([[ 0.2974, -0.6587],
       [ 0.2974, -0.6587],
       [-1.4271, -0.7679],
       [-1.4271, -0.7679]])

In [43]:
arr.repeat([2,3],axis=0)

array([[ 0.2974, -0.6587],
       [ 0.2974, -0.6587],
       [-1.4271, -0.7679],
       [-1.4271, -0.7679],
       [-1.4271, -0.7679]])

In [44]:
arr.repeat([2,3],axis=1)

array([[ 0.2974,  0.2974, -0.6587, -0.6587, -0.6587],
       [-1.4271, -1.4271, -0.7679, -0.7679, -0.7679]])

In [45]:
arr

array([[ 0.2974, -0.6587],
       [-1.4271, -0.7679]])

In [46]:
np.tile(arr,2)

array([[ 0.2974, -0.6587,  0.2974, -0.6587],
       [-1.4271, -0.7679, -1.4271, -0.7679]])

In [47]:
np.tile(arr,(2,1))

array([[ 0.2974, -0.6587],
       [-1.4271, -0.7679],
       [ 0.2974, -0.6587],
       [-1.4271, -0.7679]])

In [48]:
np.tile(arr,(3,2))

array([[ 0.2974, -0.6587,  0.2974, -0.6587],
       [-1.4271, -0.7679, -1.4271, -0.7679],
       [ 0.2974, -0.6587,  0.2974, -0.6587],
       [-1.4271, -0.7679, -1.4271, -0.7679],
       [ 0.2974, -0.6587,  0.2974, -0.6587],
       [-1.4271, -0.7679, -1.4271, -0.7679]])

In [49]:
arr = np.arange(10)*100
inds = [7,1,2,6]

In [50]:
arr[inds]

array([700, 100, 200, 600])

In [51]:
arr.take(inds)

array([700, 100, 200, 600])

In [52]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [53]:
arr.put(inds,[40,41,42,43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [54]:
inds = [2,0,1,2]
arr = randn(2,4)
arr

array([[ 1.0994, -1.7713,  0.7517,  1.6129],
       [ 1.0606, -0.1994,  0.6162, -0.2412]])

In [55]:
arr.take(inds,axis=1)

array([[ 0.7517,  1.0994, -1.7713,  0.7517],
       [ 0.6162,  1.0606, -0.1994,  0.6162]])

In [56]:
arr = randn(1000,50)
inds = np.random.permutation(1000)[:500]

In [57]:
%timeit arr[inds]

The slowest run took 342.84 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 31.8 µs per loop


In [58]:
%timeit arr.take(inds,axis=0)

The slowest run took 4.29 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 32.8 µs per loop


In [59]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [60]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [63]:
arr = randn(4,3)
arr

array([[-1.7141, -1.2398,  2.8245],
       [-0.1611, -0.0893,  1.4255],
       [ 1.0653,  0.4208,  0.241 ],
       [-0.6364,  2.0652,  0.7608]])

In [67]:
arr.mean(0)

array([-0.3616,  0.2892,  1.3129])

In [68]:
demeaned = arr -arr.mean(0)
demeaned

array([[-1.3525, -1.529 ,  1.5115],
       [ 0.2005, -0.3785,  0.1125],
       [ 1.4268,  0.1316, -1.0719],
       [-0.2748,  1.7759, -0.5521]])

In [69]:
demeaned.mean(0)

array([  0.0000e+00,   0.0000e+00,  -1.3878e-16])

In [70]:
a = np.array([[[1],[2],[3]],[[4],[5],[6]]])
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [71]:
a.shape

(2, 3, 1)

In [72]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b.shape

(3, 4)

In [73]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a +b

array([[[ 2,  3,  4,  5],
        [ 7,  8,  9, 10],
        [12, 13, 14, 15]],

       [[ 5,  6,  7,  8],
        [10, 11, 12, 13],
        [15, 16, 17, 18]]])

In [75]:
(a+b).shape

(2, 3, 4)

In [76]:
arr

array([[-1.7141, -1.2398,  2.8245],
       [-0.1611, -0.0893,  1.4255],
       [ 1.0653,  0.4208,  0.241 ],
       [-0.6364,  2.0652,  0.7608]])

In [77]:
row_means = arr.mean(1)

In [78]:
row_means

array([-0.0431,  0.3917,  0.5757,  0.7299])

In [79]:
row_means.reshape((4,1))

array([[-0.0431],
       [ 0.3917],
       [ 0.5757],
       [ 0.7299]])

In [80]:
demeaned = arr - row_means.reshape((4,1))

In [81]:
demeaned

array([[-1.6709, -1.1967,  2.8676],
       [-0.5528, -0.481 ,  1.0338],
       [ 0.4896, -0.1549, -0.3347],
       [-1.3662,  1.3353,  0.031 ]])

In [82]:
demeaned.mean(1)

array([  0.0000e+00,   7.4015e-17,  -1.8504e-17,  -7.4015e-17])

In [83]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [84]:
arr - arr.mean(1).reshape((4,1))

array([[-1.6709, -1.1967,  2.8676],
       [-0.5528, -0.481 ,  1.0338],
       [ 0.4896, -0.1549, -0.3347],
       [-1.3662,  1.3353,  0.031 ]])

In [85]:
arr = np.zeros((4,4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [86]:
arr_3d = arr[:,np.newaxis,:]

In [87]:
arr_3d

array([[[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]]])

In [88]:
arr_3d.shape

(4, 1, 4)

In [89]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-0.5969,  0.6223, -0.2349])

In [90]:
arr_1d[:,np.newaxis]

array([[-0.5969],
       [ 0.6223],
       [-0.2349]])

In [91]:
arr_1d[np.newaxis,:]

array([[-0.5969,  0.6223, -0.2349]])

In [92]:
arr = randn(3,4,5)
depth_means = arr.mean(2)

In [93]:
arr

array([[[-1.4448,  0.7249,  0.7846, -1.1636,  0.824 ],
        [-0.2934,  0.242 ,  0.6166,  1.5067,  0.5918],
        [ 0.4124,  1.2747, -0.5   ,  0.5124,  0.2198],
        [-1.6661, -1.2741,  1.2576,  0.5369,  0.4027]],

       [[-0.243 ,  0.5207, -0.2461,  0.4648,  0.0442],
        [-0.1071,  0.4657, -0.1645,  0.8809,  0.4651],
        [-0.955 , -2.2852,  0.8039, -2.2843,  0.65  ],
        [ 0.3962,  0.4189,  0.2445, -0.9155,  0.4741]],

       [[ 0.1058,  0.5851, -2.3371, -0.0415, -0.4652],
        [ 0.7643,  0.2099,  2.0485, -0.3138, -0.2156],
        [-2.4019,  1.3507,  1.0879, -2.0124,  1.2911],
        [-0.9554, -0.6898, -0.7995,  0.5194, -1.1297]]])

In [94]:
depth_means 

array([[-0.055 ,  0.5327,  0.3839, -0.1486],
       [ 0.1081,  0.308 , -0.8141,  0.1236],
       [-0.4306,  0.4987, -0.1369, -0.611 ]])

In [95]:
demeaned = arr - depth_means[:,:,np.newaxis]

In [96]:
 depth_means[:,:,np.newaxis]

array([[[-0.055 ],
        [ 0.5327],
        [ 0.3839],
        [-0.1486]],

       [[ 0.1081],
        [ 0.308 ],
        [-0.8141],
        [ 0.1236]],

       [[-0.4306],
        [ 0.4987],
        [-0.1369],
        [-0.611 ]]])

In [100]:
demeaned.mean(2)

array([[ 0.,  0., -0.,  0.],
       [-0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [101]:
def demean_axis(arr,axis=0):
    means = arr.mean(axis)
    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)]*arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [102]:
arr.ndim

3

In [107]:
indexer = [slice(None)]*arr.ndim

In [109]:
indexer[0] = np.newaxis

In [110]:
indexer

[None, slice(None, None, None), slice(None, None, None)]

In [111]:
arr = np.zeros((4,3))
arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [112]:
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [113]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:] = col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [114]:
arr[:2] = [[-1.37],[0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [115]:
arr = np.arange(10)

In [116]:
np.add.reduce(arr)

45

In [117]:
arr.sum()

45

In [130]:
arr = randn(5,5)
arr

array([[ 0.7705,  0.4863,  0.9372,  0.4111,  1.9115],
       [ 1.7209, -0.3559,  0.6293, -1.3664, -0.8741],
       [-0.0631,  0.1629,  0.4855, -0.4841, -1.8115],
       [-0.5802, -0.3295,  0.5079, -0.5407,  0.3447],
       [ 0.2262,  0.3775, -0.1813,  1.1644,  1.0196]])

In [131]:
arr[::2].sort(1)

In [132]:
arr

array([[ 0.4111,  0.4863,  0.7705,  0.9372,  1.9115],
       [ 1.7209, -0.3559,  0.6293, -1.3664, -0.8741],
       [-1.8115, -0.4841, -0.0631,  0.1629,  0.4855],
       [-0.5802, -0.3295,  0.5079, -0.5407,  0.3447],
       [-0.1813,  0.2262,  0.3775,  1.0196,  1.1644]])

In [133]:
arr[:,:-1]

array([[ 0.4111,  0.4863,  0.7705,  0.9372],
       [ 1.7209, -0.3559,  0.6293, -1.3664],
       [-1.8115, -0.4841, -0.0631,  0.1629],
       [-0.5802, -0.3295,  0.5079, -0.5407],
       [-0.1813,  0.2262,  0.3775,  1.0196]])

In [134]:
arr[:,1:]

array([[ 0.4863,  0.7705,  0.9372,  1.9115],
       [-0.3559,  0.6293, -1.3664, -0.8741],
       [-0.4841, -0.0631,  0.1629,  0.4855],
       [-0.3295,  0.5079, -0.5407,  0.3447],
       [ 0.2262,  0.3775,  1.0196,  1.1644]])

In [135]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [136]:
np.logical_and.reduce(arr[:,:-1] < arr[:,1:],axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [137]:
arr = np.arange(15).reshape((3,5))

In [138]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [139]:
arr = np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [140]:
np.multiply.outer(arr,np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [141]:
result = np.subtract.outer(randn(3,4),randn(5))
result.shape

(3, 4, 5)

In [142]:
result

array([[[-1.6391, -0.8186,  0.518 , -0.0822,  0.126 ],
        [-0.0216,  0.7989,  2.1356,  1.5354,  1.7435],
        [-3.4432, -2.6227, -1.286 , -1.8862, -1.6781],
        [-0.4565,  0.364 ,  1.7007,  1.1005,  1.3087]],

       [[-0.2215,  0.599 ,  1.9357,  1.3355,  1.5436],
        [-0.5561,  0.2644,  1.6011,  1.0008,  1.209 ],
        [-3.2333, -2.4128, -1.0761, -1.6764, -1.4682],
        [-2.66  , -1.8394, -0.5028, -1.103 , -0.8948]],

       [[-2.6389, -1.8183, -0.4817, -1.0819, -0.8737],
        [-1.3132, -0.4927,  0.844 ,  0.2437,  0.4519],
        [-1.9094, -1.0889,  0.2478, -0.3524, -0.1442],
        [-2.6591, -1.8386, -0.5019, -1.1021, -0.894 ]]])

In [143]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.add.reduceat(arr,[0,5,8])

array([10, 18, 17])

In [146]:
arr = np.multiply.outer(np.arange(4),np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [147]:
np.add.reduceat(arr,[0,2,4],axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [148]:
def add_elements(x,y):
    return x+y

In [150]:
add_them = np.frompyfunc(add_elements,2,1)
add_them(np.arange(8),np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [151]:
add_them = np.vectorize(add_elements,otypes=[np.float64])

In [152]:
add_them(np.arange(8),np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [153]:
arr = randn(1000)

In [154]:
%timeit add_them(arr,arr)

1000 loops, best of 3: 345 µs per loop


In [155]:
%timeit np.add(arr,arr)

The slowest run took 141.48 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 1.67 µs per loop


In [156]:
dtype = [('x',np.float64),('y',np.int32)]

In [157]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [158]:
sarr[0]

(1.5, 6)

In [159]:
sarr[0]['y']

6

In [160]:
sarr['x']

array([ 1.5   ,  3.1416])

In [161]:
dtype = [('x',np.int64,3),('y',np.int32)]

In [162]:
arr = np.zeros(4,dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [163]:
arr[0]['x']

array([0, 0, 0])

In [164]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [165]:
dtype = [('x',[('a','f8'),('b','f4')]),('y',np.int32)]
data = np.array([((1,2),5),((3,4),6)],dtype=dtype)
data['x']

array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('a', '<f8'), ('b', '<f4')])

In [166]:
data['y']

array([5, 6], dtype=int32)

In [167]:
data['x']['a']

array([ 1.,  3.])

In [169]:
arr = randn(6)
arr

array([ 0.7093, -0.0494,  1.2886,  0.4404, -1.0819, -0.1789])

In [170]:
arr.sort()

In [171]:
arr

array([-1.0819, -0.1789, -0.0494,  0.4404,  0.7093,  1.2886])

In [172]:
arr = randn(3,5)
arr

array([[ 0.6984,  1.1012, -1.3259, -0.5677,  0.1762],
       [ 1.4609,  0.8148, -0.7871,  1.3622,  0.1198],
       [-0.4253,  1.5526, -0.2399,  0.1332,  1.1615]])

In [173]:
arr[:,0].sort()
arr

array([[-0.4253,  1.1012, -1.3259, -0.5677,  0.1762],
       [ 0.6984,  0.8148, -0.7871,  1.3622,  0.1198],
       [ 1.4609,  1.5526, -0.2399,  0.1332,  1.1615]])

In [174]:
arr = randn(5)
arr

array([-0.9954, -0.5895,  0.6958, -1.0429, -1.7312])

In [175]:
np.sort(arr)

array([-1.7312, -1.0429, -0.9954, -0.5895,  0.6958])

In [176]:
arr

array([-0.9954, -0.5895,  0.6958, -1.0429, -1.7312])

In [177]:
arr = randn(3,5)
arr

array([[ 0.6762, -0.0834,  0.4944, -0.2054,  0.4086],
       [ 0.3151,  0.0534,  0.7502,  0.2624, -1.15  ],
       [ 0.2784,  0.2222,  0.9038, -1.1807,  0.2945]])

In [178]:
arr.sort(axis=1)
arr

array([[-0.2054, -0.0834,  0.4086,  0.4944,  0.6762],
       [-1.15  ,  0.0534,  0.2624,  0.3151,  0.7502],
       [-1.1807,  0.2222,  0.2784,  0.2945,  0.9038]])

In [180]:
arr[:,::-1]

array([[ 0.6762,  0.4944,  0.4086, -0.0834, -0.2054],
       [ 0.7502,  0.3151,  0.2624,  0.0534, -1.15  ],
       [ 0.9038,  0.2945,  0.2784,  0.2222, -1.1807]])

In [183]:
values = np.array([5,0,1,3,2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [184]:
values[indexer]

array([0, 1, 2, 3, 5])

In [185]:
arr = randn(3,5)
arr

array([[ 0.0633,  0.7517,  0.6486,  0.6016, -1.5721],
       [-1.0595,  0.2293,  0.324 ,  0.695 ,  0.5051],
       [-0.3793, -0.5039,  0.3883, -0.4916,  0.284 ]])

In [187]:
arr[0] = values
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-1.0595,  0.2293,  0.324 ,  0.695 ,  0.5051],
       [-0.3793, -0.5039,  0.3883, -0.4916,  0.284 ]])

In [188]:
arr[:,arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [ 0.2293,  0.324 ,  0.5051,  0.695 , -1.0595],
       [-0.5039,  0.3883,  0.284 , -0.4916, -0.3793]])

In [190]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [191]:
sorter = np.lexsort((first_name,last_name))

In [192]:
sorter

array([1, 2, 3, 0, 4])

In [193]:
zip(last_name[sorter],first_name[sorter])

In [194]:
values = np.array(['2:first','2:second','1:first','1:second','1:third'])
key = np.array([2,2,1,1,1])

In [195]:
values

array(['2:first', '2:second', '1:first', '1:second', '1:third'], 
      dtype='<U8')

In [196]:
key

array([2, 2, 1, 1, 1])

In [197]:
indexer = key.argsort(kind='mergesort')

In [198]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='<U8')

In [199]:
indexer

array([2, 3, 4, 0, 1])

In [200]:
arr = np.array([0,1,7,12,15])
arr.searchsorted(9)

3

In [202]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5])

In [203]:
arr = np.array([0,0,0,1,1,1,1])
arr.searchsorted([0,1])

array([0, 3])

In [204]:
arr.searchsorted([0,1],side='right')

array([3, 7])

In [205]:
data = np.floor(np.random.uniform(0,10000,size=50))

In [208]:
data

array([ 8758.,  7883.,  1130.,  4130.,  9020.,  6384.,  5953.,  9720.,
        9653.,  2572.,  8718.,  4482.,  4348.,  5883.,  7149.,  2428.,
        5064.,  4417.,  6695.,  8208.,  6141.,  1197.,  9407.,  7125.,
        4418.,  9977.,  9022.,  4049.,  2308.,  4483.,  8980.,  3571.,
        3252.,  3722.,  1862.,  1626.,  9340.,  5018.,  8938.,  2299.,
        4484.,  9842.,  3633.,   227.,  4664.,  1360.,   760.,  7939.,
        6587.,  1090.])

In [209]:
bins = np.array([0,100,1000,5000,10000])

In [210]:
labels = bins.searchsorted(data)
labels

array([4, 4, 3, 3, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4,
       4, 3, 4, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 4, 3, 2, 3, 3,
       2, 4, 4, 3])

In [211]:
Series(data).groupby(labels).mean()

2     493.500000
3    3109.782609
4    7896.160000
dtype: float64

In [212]:
np.digitize(data,bins)

array([4, 4, 3, 3, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4,
       4, 3, 4, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 4, 3, 2, 3, 3,
       2, 4, 4, 3])

In [213]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:,0]

array([ 8.8277,  3.8222, -1.1428,  2.0441])

In [214]:
y = X[:,:1]

In [215]:
X

array([[ 8.8277,  3.8222, -1.1428,  2.0441],
       [ 3.8222,  6.7527,  0.8391,  2.0829],
       [-1.1428,  0.8391,  5.0169,  0.7957],
       [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [216]:
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [217]:
np.dot(y.T,np.dot(X,y))

array([[ 1195.468]])

In [218]:
Xm = np.matrix(X)

In [219]:
ym = Xm[:,0]

In [220]:
Xm

matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [221]:
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [222]:
ym.T*Xm*ym

matrix([[ 1195.468]])

In [223]:
arr_c = np.ones((1000,1000),order='C')
arr_f = np.ones((1000,1000),order='F')

In [234]:
%timeit arr_c.sum(1)

The slowest run took 13.59 times longer than the fastest. This could mean that an intermediate result is being cached 
1000 loops, best of 3: 836 µs per loop


In [235]:
%timeit arr_f.sum(1)

1000 loops, best of 3: 786 µs per loop
