In [1]:
from numpy.random import randn
import numpy as np

In [10]:
'標準正規分布から2×3行列の乱数を抽出'
data = randn(2, 3)

In [11]:
data

array([[-0.33435051,  0.52297594, -1.41199994],
       [ 0.58147751,  0.63174137, -0.68841674]])

In [12]:
data *10

array([[ -3.34350512,   5.22975945, -14.11999936],
       [  5.81477511,   6.31741365,  -6.88416743]])

In [13]:
data +data

array([[-0.66870102,  1.04595189, -2.82399987],
       [ 1.16295502,  1.26348273, -1.37683349]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

4.1.1 ndarrayの生成

In [16]:
data1 = [6 ,7.5,8,0,1]

In [17]:
arr1 = np.array(data1)

In [18]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [19]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [20]:
arr2 =np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.empty((2,3,2))

array([[[  0.00000000e+000,  -2.00000012e+000],
        [  2.20501577e-314,   2.20502007e-314],
        [  2.20502064e-314,   2.20492022e-314]],

       [[  2.75859453e-313,   0.00000000e+000],
        [  2.13981517e-314,   6.36598737e-311],
        [  0.00000000e+000,   8.34402832e-309]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
'単位行列の作成'
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [44]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)

In [45]:
arr1.dtype , arr2.dtype

(dtype('float64'), dtype('int32'))

In [46]:
arr = np.array([1,2,3,4,5])

In [47]:
arr.dtype

dtype('int64')

In [48]:
float_arr = arr.astype(np.float64)

In [49]:
float_arr.dtype

dtype('float64')

In [50]:
arr = np.array([3.7,-1.2, -2.6, 0.5, 12.9, 10.1])

In [51]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [52]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [53]:
numeric_strings = np.array(['1.25','9.6','42'],dtype = np.string_)

In [54]:
numeric_strings.astype(float) 

array([  1.25,   9.6 ,  42.  ])

In [55]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [56]:
empty_uint32 = np.empty(8,dtype= 'u4')

In [57]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [3]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [9]:
arr*arr;
arr-arr;
1/arr;
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [6]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [7]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [8]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d
arr2d[2]

array([7, 8, 9])

In [27]:
arr2d[0][2]

3

In [28]:
arr2d[0,2]

3

In [66]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
old_values = arr3d[0].copy()


In [69]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
old_values 

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr3d[1,0]

array([7, 8, 9])

In [73]:
arr3d[1,0,1]

8

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [10]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [22]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [15]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr2d[1,:2]

array([4, 5])

In [19]:
arr2d[2,:1]

array([7])

In [20]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [21]:
arr2d[:2,1:] = 0

In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7,4)

In [24]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [38]:
data

array([[ 0.19557342,  0.74698149, -0.14429393,  0.49464992],
       [ 1.12345754,  2.20671218, -0.81534026, -1.5847606 ],
       [-1.21279017, -1.7261107 ,  0.63089383, -0.06310808],
       [ 0.82636581, -0.85587211, -0.11832175,  1.19376709],
       [ 1.10266293, -0.37505416,  0.48363246, -2.10297548],
       [-1.2954518 ,  0.22222804, -0.53501416, -0.58533718],
       [-0.26510317,  1.53428452, -0.27610628,  0.69832313]])

In [28]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [29]:
data[names=='Bob']

array([[ 0.19557342,  0.74698149, -0.14429393,  0.49464992],
       [ 0.82636581, -0.85587211, -0.11832175,  1.19376709]])

In [32]:
data[names=='Bob',2:]

array([[-0.14429393,  0.49464992],
       [-0.11832175,  1.19376709]])

In [33]:
data[names == 'Bob',3]

array([ 0.49464992,  1.19376709])

In [35]:
mask=(names=='Bob')|(names== 'Will')

In [36]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [37]:
data[mask,]

array([[ 0.19557342,  0.74698149, -0.14429393,  0.49464992],
       [-1.21279017, -1.7261107 ,  0.63089383, -0.06310808],
       [ 0.82636581, -0.85587211, -0.11832175,  1.19376709],
       [ 1.10266293, -0.37505416,  0.48363246, -2.10297548]])

In [40]:
data[data<0] =0

In [41]:
data

array([[ 0.19557342,  0.74698149,  0.        ,  0.49464992],
       [ 1.12345754,  2.20671218,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.63089383,  0.        ],
       [ 0.82636581,  0.        ,  0.        ,  1.19376709],
       [ 1.10266293,  0.        ,  0.48363246,  0.        ],
       [ 0.        ,  0.22222804,  0.        ,  0.        ],
       [ 0.        ,  1.53428452,  0.        ,  0.69832313]])

In [42]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [43]:
data[names != 'Joe']=7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.12345754,  2.20671218,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.22222804,  0.        ,  0.        ],
       [ 0.        ,  1.53428452,  0.        ,  0.69832313]])

In [45]:
arr = np.empty((8,4))
arr

array([[  0.00000000e+000,   0.00000000e+000,   9.38724727e-323,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  2.20504883e-314,   2.20504883e-314,   0.00000000e+000,
          0.00000000e+000],
       [  2.20504883e-314,   2.20504883e-314,   2.20504883e-314,
          2.20494358e-314]])

In [47]:
for i in range(8):
    arr[i] = i

In [48]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [49]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [50]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [52]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [53]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [55]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [56]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [58]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [61]:
arr = np.random.randn(6,3) 
arr

array([[-0.50745596,  1.82973607, -2.23605698],
       [-1.35455829,  0.80471727,  0.66627255],
       [ 0.25167456, -0.0530458 ,  0.05220248],
       [-0.24510759,  0.75641934, -0.6784637 ],
       [-1.45725704,  0.31662441,  0.20874213],
       [ 1.11766323, -1.41053556, -1.38897857]])

In [62]:
np.dot(arr.T,arr)

array([[ 5.58852671, -4.2552082 , -1.44497114],
       [-4.2552082 ,  6.66034962, -2.04590875],
       [-1.44497114, -2.04590875,  7.87974277]])

In [100]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
arr.transpose((0,2,1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [121]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [119]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])