In [89]:
from numpy.random import randn
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

In [94]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.sqrt(arr)

array([ 0.    ,  1.    ,  1.4142,  1.7321,  2.    ,  2.2361,  2.4495,
        2.6458,  2.8284,  3.    ])

In [96]:
np.exp(arr)

array([    1.    ,     2.7183,     7.3891,    20.0855,    54.5982,
         148.4132,   403.4288,  1096.6332,  2980.958 ,  8103.0839])

In [97]:
x = randn(8)
y = randn(8)
x

array([-0.0114, -1.5774,  0.634 , -0.6223,  0.3501, -1.5923,  0.513 ,
        0.3435])

In [7]:
y

array([-0.62193523,  1.57389057, -1.31752352, -1.90670796, -0.11668851,
        0.29088303, -1.00760539,  0.08376809])

In [9]:
np.maximum(x,y)

array([ 0.99683109,  1.57389057,  0.16366663, -0.88691606, -0.11668851,
        0.29088303, -1.00760539,  0.08376809])

In [11]:
arr = randn(7)*5
arr

array([-2.33803895,  2.54565865,  2.97552827, -6.91854734, -4.56039952,
       -5.17784243, -6.44337837])

In [14]:
np.modf(arr)[0]

array([-0.33803895,  0.54565865,  0.97552827, -0.91854734, -0.56039952,
       -0.17784243, -0.44337837])

In [20]:
points = np.arange(-5,5,0.01)
xs,ys = np.meshgrid(points,points)

In [21]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [22]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [25]:
z = np.sqrt(xs**2+ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [26]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

In [27]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [31]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
cond

array([ True, False,  True,  True, False], dtype=bool)

In [32]:
result = np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [33]:
arr = randn(4,4)
arr

array([[-0.06584756,  0.79708129,  0.57989694, -0.28259954],
       [-1.05602975, -0.59229962,  0.86458132, -1.14868432],
       [-0.97165017,  0.55173601,  1.05255576, -0.03359162],
       [-0.80652554, -0.30795715, -0.05793074,  0.63626218]])

In [34]:
np.where(arr>0,2,-2)

array([[-2,  2,  2, -2],
       [-2, -2,  2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2,  2]])

In [35]:
np.where(arr>0,2,arr)

array([[-0.06584756,  2.        ,  2.        , -0.28259954],
       [-1.05602975, -0.59229962,  2.        , -1.14868432],
       [-0.97165017,  2.        ,  2.        , -0.03359162],
       [-0.80652554, -0.30795715, -0.05793074,  2.        ]])

In [44]:
arr = randn(5,4)
arr

array([[-0.87080608,  1.48063221, -0.48332212,  0.9290732 ],
       [ 1.69009727,  1.10049478, -0.22462943, -0.16615028],
       [ 1.02873565,  0.74713049,  0.83775351, -0.70091915],
       [-0.2711914 , -0.1710623 ,  1.01988439, -0.04099304],
       [-1.8060899 , -2.12493578,  0.36692642, -0.65781691]])

In [39]:
np.mean(arr)

0.15805053776376971

In [40]:
arr.sum()

3.1610107552753939

In [41]:
#axisは0が列方向、1が行方向
arr.mean(axis=1)

array([-0.61620133,  0.82421593,  0.33919446,  0.28285389, -0.03981026])

In [50]:
arr.sum(0)

array([-0.22925445,  1.0322594 ,  1.51661276, -0.63680619])

In [51]:
arr.sum(axis=0)

array([-0.22925445,  1.0322594 ,  1.51661276, -0.63680619])

In [52]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [54]:
arr.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [55]:
arr = randn(100)
(arr>0).sum()

48

In [56]:
bools = np.array([True,False,True,True,False])
bools.any()

True

In [57]:
bools.all()

False

In [58]:
arr =randn(8)
arr

array([-0.52653882,  1.65274501,  0.45843175, -0.88078512,  1.31570593,
       -0.37730021,  0.32595196,  1.73819056])

In [60]:
arr.sort()
arr

array([-0.88078512, -0.52653882, -0.37730021,  0.32595196,  0.45843175,
        1.31570593,  1.65274501,  1.73819056])

In [62]:
arr= randn(5,3)
arr

array([[ 0.16620544, -0.43353283, -0.27929221],
       [ 0.03724952,  1.94022106,  1.90739623],
       [-0.65489293,  0.65905831,  0.96099598],
       [ 1.09518401,  0.19733985,  0.35954878],
       [-0.37901059, -0.40548379, -0.41279366]])

In [64]:
arr.sort(0)
arr

array([[-0.65489293, -0.40548379, -0.37901059],
       [-0.43353283, -0.27929221,  0.16620544],
       [-0.41279366,  0.35954878,  0.96099598],
       [ 0.03724952,  0.65905831,  1.09518401],
       [ 0.19733985,  1.90739623,  1.94022106]])

In [65]:
np.sort(arr,axis=0)

array([[-0.65489293, -0.40548379, -0.37901059],
       [-0.43353283, -0.27929221,  0.16620544],
       [-0.41279366,  0.35954878,  0.96099598],
       [ 0.03724952,  0.65905831,  1.09518401],
       [ 0.19733985,  1.90739623,  1.94022106]])

In [66]:
large_arr = randn(1000)

In [67]:
large_arr.sort()

In [70]:
large_arr[int(0.05*len(large_arr))]

-1.6224242909465145

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [72]:
np.in1d(ints,[2,3,6])

array([ True,  True,  True,  True,  True, False, False, False, False], dtype=bool)

In [73]:
arr = np.arange(10)

In [74]:
np.save('some_array',arr)

In [75]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.savez('array_archives.npz',a=arr,b=arr)

In [77]:
arch = np.load('array_archives.npz')

In [78]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [80]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [81]:
np.dot(x,y)

array([[  28.,   64.],
       [  67.,  181.]])

In [83]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [84]:
from numpy.linalg import inv,qr

In [85]:
X = randn(5,5)
mat = X.T.dot(X)

In [92]:
mat

array([[ 2.8906, -0.6587,  1.371 ,  1.563 , -0.6786],
       [-0.6587,  5.1025,  0.6619, -1.2497,  0.5462],
       [ 1.371 ,  0.6619,  1.2682,  0.9664,  0.2923],
       [ 1.563 , -1.2497,  0.9664,  1.4414, -0.1956],
       [-0.6786,  0.5462,  0.2923, -0.1956,  3.8255]])

In [91]:
inv(mat)

array([[  1.3714,   1.0621,  -3.5996,   1.9102,   0.4644],
       [  1.0621,   4.4868, -12.1095,  10.9979,   1.0356],
       [ -3.5996, -12.1095,  34.9073, -30.4251,  -3.1331],
       [  1.9102,  10.9979, -30.4251,  28.9058,   2.5718],
       [  0.4644,   1.0356,  -3.1331,   2.5718,   0.5669]])

In [90]:
np.dot(mat,inv(mat))

array([[ 1., -0.,  0.,  0.,  0.],
       [ 0.,  1., -0., -0., -0.],
       [-0.,  0.,  1., -0., -0.],
       [-0.,  0.,  0.,  1.,  0.],
       [-0., -0.,  0., -0.,  1.]])

In [98]:
q,r = qr(mat)

In [99]:
q

array([[-0.7846, -0.1514,  0.2586,  0.5316,  0.1093],
       [ 0.1788, -0.9466,  0.0677, -0.0888,  0.2438],
       [-0.3721, -0.2648, -0.4177, -0.2698, -0.7377],
       [-0.4243,  0.0951, -0.4146, -0.5219,  0.6055],
       [ 0.1842, -0.042 , -0.763 ,  0.6035,  0.1335]])

In [100]:
r

array([[-3.6841,  1.8137, -1.7854, -2.457 ,  1.309 ],
       [ 0.    , -5.0476, -1.0904,  0.8358, -0.6711],
       [ 0.    ,  0.    , -0.7541, -0.5324, -3.0985],
       [ 0.    ,  0.    ,  0.    , -0.1891,  1.9228],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.2354]])

In [101]:
samples = np.random.normal(size=(4,4))
samples

array([[ 0.793 , -1.0288,  1.306 , -1.6996],
       [ 0.2826, -0.1213,  1.6396, -0.1501],
       [ 0.1512,  1.4   , -0.0678,  0.0021],
       [ 0.5449, -0.7928,  0.4063,  0.0045]])

In [102]:
nsteps = 1000

In [107]:
draws = np.random.randint(0,2,size= nsteps)

In [108]:
steps = np.where(draws>0,1,-1)

In [110]:
walk = steps.cumsum() 

In [112]:
walk.max()

27

In [114]:
walk.min()

-20

In [118]:
(np.abs(walk)>= 10).argmax()

97

In [119]:
nwalks = 5000

In [120]:
nsteps = 1000

In [121]:
draws = np.random.randint(0,2,size=(nwalks,nsteps))

In [122]:
steps = np.where(draws >0,1,-1)

In [165]:
walks = steps.cumsum(1)

In [166]:
walks

array([[  1,   2,   3, ..., 948, 949, 950],
       [  1,   2,   3, ..., 954, 955, 956],
       [  1,   2,   3, ..., 964, 965, 966],
       ..., 
       [  1,   2,   3, ..., 952, 953, 954],
       [  1,   2,   3, ..., 980, 981, 982],
       [  1,   2,   3, ..., 948, 949, 950]])

In [167]:
walks.max()

984

In [168]:
walks.min()

-2

In [169]:
hits30 = (np.abs(walks)>=30).any(1)

In [170]:
hits30

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [171]:
hits30.sum()

5000

In [172]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)

In [173]:
crossing_times.mean()

30.4452

In [163]:
steps = np.where(np.random.normal(loc =  1,scale=0.5,size=(nwalks,nsteps))>0,1,-1)

In [164]:
steps

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ..., 
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])